### ISSUE TITLE
hey failed to conect to server kindly rectify on that

### ISSUE THREAD

**Issue by moseuh** [deepcpatel/GreenDoc#2]
failed to coonect to server ...can you send the apk please mosesmaweu46@GMAIL.COM

**Comment by deepcpatel** [comment]
Hi, please add your server URL at this [line](https://github.com/deepcpatel/GreenDoc/blob/e91799b718d9bb48d5569e511a5776282717fec0/android_app/app/src/main/java/com/jayvaghasiya/test/Main2Activity.java#L162) in the code and your server must allow the POST requests. Also, we have provided the Android code in our repo, so you can compile it to an APK.

**Comment by moseuh** [comment]
Kindly send the apk please

**Comment by moseuh** [comment]
Have changed the server url to local Host and the app still shows the toast
message you can't connect to the server

**Comment by moseuh** [comment]
It cmumicated to the server but it's not displaying results

**Comment by moseuh** [comment]
The server got connected but it is not displaying results.....if i
uncomment the disease string it only gives the string name results ..kindly
assist

**Comment by moseuh** [comment]
ITS NOT DISPLAYING RESULTS

**Comment by deepcpatel** [comment]
Did you found any error message in your console?

**Comment by moseuh** [comment]
There was no error it's only that it couldn't identify any disease

On Mar 30, 2020 11:49 AM, "Deep C. Patel" <notifications@github.com> wrote:

Did you found any error message in your console?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/deepcpatel/GreenDoc/issues/2#issuecomment-605867894>,
or unsubscribe

**Comment by deepcpatel** [comment]
I got that! We have only shown Tomato related diseases as of now in our Android app. But, you can add more diseases [here](https://github.com/deepcpatel/GreenDoc/tree/master/android_app/app/src/main/assets/causesremedies.json). Our ML model is capable of classifying all the disease given in the dataset. Its just that you have to add them to the JSON file of the Android app.

**Comment by moseuh** [comment]
Av tried all that and it's not even recognizing even a single disease

On Mar 31, 2020 7:53 PM, "Deep C. Patel" <notifications@github.com> wrote:

I got that. We have only shown Tomato related disease as of now in our
Android app. But, you can add more disease here
<https://github.com/deepcpatel/GreenDoc/tree/master/android_app/app/src/main/assets/causesremedies.json>.
Our ML model is capable of classifying all the disease given in the
dataset. Its just that you have to add them to the JSON file.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/deepcpatel/GreenDoc/issues/2#issuecomment-606747865>,
or unsubscribe

**Comment by deepcpatel** [comment]
Since we have trained our model on the PlantVillage dataset, they may not be similar to your phone images. You can retrain the model on the Phone images. We have provided the training and testing scripts in our repo.
