### ISSUE TITLE
How to get the class name except from "Tomato" in inference.py?

### ISSUE THREAD

**Issue by JenniferKuo** [deepcpatel/GreenDoc#3]
Hi there,
I want to use your pretrained model to test my own plant photo.
But in the inference.py file, the class is constrained to tomato for mobile app.
So how do I get the original class name for the predict index result?
Thanks!
Appreciate for your nice work!

**Comment by deepcpatel** [comment]
In function `init_idx_dict(self)` in `inference.py` file, we have constrained our model to only output Tomato related diseases. However, based on the given image, our trained model is capable to output all the classes from `1` to `37` as shown below: 

`Classes: ['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy', 'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy', 'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy', 'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus', 'Tomato___healthy', 'background']`

The only changes you have to do in `inference.py` is to extend the `self.idx_to_name` with more disease classes and modify or remove this [if](https://github.com/deepcpatel/GreenDoc/blob/63623d353993fc3a364a8dccfd159b8587e78dcb/server_and_model/modules/inference.py#L70) block (which is randomly assigning disease name if the prediction is for the plants other than Tomato).

Moreover, you need to add some disease-related information in [causesremedies.json](https://github.com/deepcpatel/GreenDoc/blob/master/android_app/app/src/main/assets/causesremedies.json) file of the Android app if you wish.

Thank you for your appreciation!

**Comment by JenniferKuo** [comment]
> In function `init_idx_dict(self)` in `inference.py` file, we have constrained our model to only output Tomato related diseases. However, based on the given image, our trained model is capable to output all the classes from `1` to `37` as shown below:
> 
> `Classes: ['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy', 'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy', 'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy', 'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus', 'Tomato___healthy', 'background']`
> 
> The only changes you have to do in `inference.py` is to extend the `self.idx_to_name` with more disease classes and modify or remove this [if](https://github.com/deepcpatel/GreenDoc/blob/63623d353993fc3a364a8dccfd159b8587e78dcb/server_and_model/modules/inference.py#L70) block (which is randomly assigning disease name if the prediction is for the plants other than Tomato).
> 
> Moreover, you need to add some disease-related information in [causesremedies.json](https://github.com/deepcpatel/GreenDoc/blob/master/android_app/app/src/main/assets/causesremedies.json) file of the Android app if you wish.
> 
> Thank you for your appreciation!

This is what I need, thank you!
